import type { Metadata } from "next";
import {  Geist_Mono,Roboto } from "next/font/google";
import "./globals.css";
import DashboardWarpper from "./DashboardWarpper";


const geistRoboto = Roboto({
  variable: "--font-geist-robot",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistRoboto.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <DashboardWarpper>

        {children}
        </DashboardWarpper>
        
        </body>
    </html>
  );
}
